#!/usr/bin/zsh

alias ls='ls -laF --color=auto -h  --group-directories-first'
alias rm='rm -i'

#git aliases
alias pgl="git log --all --decorate --oneline --graph --abbrev-commit --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'"
