#!/usr/bin/zsh

ZSH_THEME="agnoster"

PATH=$PATH:'/mnt/c/program files/dotnet/dotnet.exe'
PATH=$PATH:"$HOME/bin"

source ~/bin/aliases


RED='\033[0;31m'
echo -e "${RED}Zsh Manual Configuration Done!"
